from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
import os
import datetime

# This configures the database. You need to set the env variable DB_HOST for it to work. 
# the db host should be the url of 
DB_HOST = os.environ.get('DB_HOST')
app = Flask(__name__)
app.config['SQLALCHEMY_DATABASE_URI'] = 'postgresql://census@%s/census' % DB_HOST
db = SQLAlchemy(app)

class OriginDestination(db.Model):
	__tablename__ = 'origin_destination'
	h_geocode 	= db.Column(db.String(15),nullable=False,primary_key=True)
	w_geocode 	= db.Column(db.String(15),nullable=False,primary_key=True)
 	s000      	= db.Column(db.Integer) 
 	sa01      	= db.Column(db.Integer) 
 	sa02      	= db.Column(db.Integer) 
 	sa03	  	= db.Column(db.Integer) 
	se01	  	= db.Column(db.Integer) 
 	se02	  	= db.Column(db.Integer) 
 	se03	  	= db.Column(db.Integer) 
 	si01	  	= db.Column(db.Integer) 
 	si02	  	= db.Column(db.Integer) 
 	si03	  	= db.Column(db.Integer)  
 	createdate 	= db.Column(db.Date)    
 	data_year 	= db.Column(db.Integer, nullable=False,primary_key=True) 
 	job_type  	= db.Column(db.String(255), nullable=False,primary_key=True)
 	## make an __repr__ 

class WorkAreaDetail(db.Model):
	__tablename__ = 'work_area_detail'
	geocode              = db.Column(db.String(15),nullable=False,primary_key=True)
	age_29_under         = db.Column(db.Integer)                
	age_30_54            = db.Column(db.Integer)                
	age_55_over          = db.Column(db.Integer)                
	earnings_1250_under  = db.Column(db.Integer)                
	earnings_1251_3333   = db.Column(db.Integer)                
	earnings_3333_over   = db.Column(db.Integer)                
	cns01                = db.Column(db.Integer)                
	cns02                = db.Column(db.Integer)                
	cns03                = db.Column(db.Integer)                
	cns04                = db.Column(db.Integer)                
	cns05                = db.Column(db.Integer)                
	cns06                = db.Column(db.Integer)                
	cns07                = db.Column(db.Integer)                
	cns08                = db.Column(db.Integer)                
	cns09                = db.Column(db.Integer)                
	cns10                = db.Column(db.Integer)                
	cns11                = db.Column(db.Integer)                
	cns12                = db.Column(db.Integer)                
	cns13                = db.Column(db.Integer)                
	cns14                = db.Column(db.Integer)                
	cns15                = db.Column(db.Integer)                
	cns16                = db.Column(db.Integer)                
	cns17                = db.Column(db.Integer)                
	cns18                = db.Column(db.Integer)                
	cr19                 = db.Column(db.Integer)                
	cr20                 = db.Column(db.Integer)                
	cr01                 = db.Column(db.Integer)                
	cr02                 = db.Column(db.Integer)                
	cr03                 = db.Column(db.Integer)                
	cr04                 = db.Column(db.Integer)                
	cr05                 = db.Column(db.Integer)                
	cr06                 = db.Column(db.Integer)                
	cr07                 = db.Column(db.Integer)                
	ct01                 = db.Column(db.Integer)                
	ct02                 = db.Column(db.Integer)                
	cd01                 = db.Column(db.Integer)                
	cd02                 = db.Column(db.Integer)                
	cd03                 = db.Column(db.Integer)                
	cd04                 = db.Column(db.Integer)                
	cs01                 = db.Column(db.Integer)                
	cs02                 = db.Column(db.Integer)                
	cfa01                = db.Column(db.Integer)                
	cfa02                = db.Column(db.Integer)                
	cfa03                = db.Column(db.Integer)                
	cfa04                = db.Column(db.Integer)                
	cfa05                = db.Column(db.Integer)                
	cfs01                = db.Column(db.Integer)                
	cfs02                = db.Column(db.Integer)                
	cfs03                = db.Column(db.Integer)                
	cfs04                = db.Column(db.Integer)                
	cfs05                = db.Column(db.Integer)                
	createdate           = db.Column(db.Date)                   
	area_type            = db.Column(db.String(255),nullable=False,primary_key=True)
	data_year            = db.Column(db.Integer, nullable=False,primary_key=True)               
	job_type             = db.Column(db.String(255),nullable=False,primary_key=True)
	segment              = db.Column(db.String(255),nullable=False,primary_key=True)
	## make a repr ## 

# Tests
print OriginDestination.query.limit(1).all()
print WorkAreaDetail.query.limit(1).all()
